server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
#    password: "purpbelieves"
#    url: "jdbc:mysql://mysql-firramo.alwaysdata.net/firramo_db?reconnect=true"
#    username: "firramo"
    password:
    url: "jdbc:mysql://localhost:3306/firramo_db?reconnect=true"
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false